apiVersion: v1
kind: Namespace
metadata:
  name: grafana-agent
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cloud-secrets
  namespace: grafana-agent
  labels:
    lastpass-secret: "true"
data:
  loki-endpoint: loki-endpoint
  loki-user: loki-user
  loki-api: grafanacloud-api
  prom-user: prom-user
  prom-api: grafanacloud-api
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana-agent
  namespace: grafana-agent
spec:
  url:  https://grafana.github.io/helm-charts
  interval: 10m
---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: grafana-agent
spec:
  interval: 5m
  values:
    kubeletService:
      namespace: default
      serviceName: kubelet
  chart:
    spec:
      version: 0.1.2
      chart: grafana-agent-operator
      sourceRef:
        kind: HelmRepository
        name: grafana-agent
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: grafana-agent
  labels:
    app: grafana-agent
spec:
  image: grafana/agent:v0.20.0
  logLevel: info
  serviceAccountName: grafana-agent
  metrics:
    instanceSelector:
      matchLabels:
        agent: grafana-agent

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: grafana-agent

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  - /metrics/cadvisor
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
- kind: ServiceAccount
  name: grafana-agent
  namespace: grafana-agent
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: primary
  namespace: grafana-agent
  labels:
    agent: grafana-agent
spec:
  remoteWrite:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basicAuth:
      username:
        name: grafana-cloud-secrets
        key: prom-user
      password:
        name: grafana-cloud-secrets
        key: prom-api

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace.
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      instance: primary

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace.
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      instance: primary

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace.
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      instance: primary