apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: agent-self
  namespace: agent
  labels:
    instance: primary
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/name": grafana-agent
  podMetricsEndpoints:
  - port: http-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  namespace: traefik
  labels:
    instance: primary
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/name": traefik
  podMetricsEndpoints:
  - port: metrics