apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lastpass
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lastpass
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lastpass
subjects:
- kind: ServiceAccount
  name: lastpass-controller
  namespace: lastpass-controller

---
apiVersion: v1
data:
  test: "test-secret"
kind: ConfigMap
metadata:
  labels:
    lastpass-secret: "true"
  name: test-secret
  namespace: lastpass-controller