kind: Namespace
apiVersion: v1
metadata:
  name: metallb

---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  url:  https://metallb.github.io/metallb
  interval: 10m

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 5m
  values:
    existingConfigMap: "metallb-config"
  chart:
    spec:
      version: 0.11.0
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: metallb-config
data:
  config: |
    peers:
    - peer-address: 10.0.0.1
      peer-asn: 64512
      my-asn: 64512
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.42.0.0-10.42.0.254
      avoid-buggy-ips: true