apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: kube-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 10m

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: kube-system
spec:
  interval: 5m
  values:
    prometheus:
      monitor:
        enabled: true
        additionalLabels:
          instance: primary
  chart:
    spec:
      version: 3.0.0
      chart: prometheus-node-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
