kind: Namespace
apiVersion: v1
metadata:
  name: metallb

---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb
spec:
  url:  https://metallb.github.io/metallb
  interval: 10m

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 5m
  chart:
    spec:
      version: 0.11.0
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb