apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  url:  https://metallb.github.io/metallb
  interval: 10m

---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart: metallb
  version: 0.11.0
  sourceRef:
    name: metallb
    kind: HelmRepository
  interval: 5m

---

apiVersion: helm.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmChart
        name: metallb