kind: Namespace
apiVersion: v1
metadata:
  name: traefik

---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  url:  https://helm.traefik.io/traefik
  interval: 10m

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  values:
  chart:
    spec:
      version: 10.6.1
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
