apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: homenet
  namespace: flux-system
spec:
  interval: 5m
  path: "./manifests"
  sourceRef:
    kind: GitRepository
    name: homenet
  wait: true
  prune: true
  timeout: 2m