server:
  log_level: "info"
metrics:
  global:
    external_labels:
      host: ${host}
    remote_write:
      - url: "https://prometheus-us-central1.grafana.net/api/prom/push"
        basic_auth:
          username: 38514
          password: ${password}
  configs:
    - name: gcloud
      scrape_configs:
        - job_name: docker
          docker_sd_configs:
            - host: "unix:///var/run/docker.sock"
          relabel_configs:
            # Only keep containers that have a `prometheus-job` label.
            - source_labels: [__meta_docker_container_label_prometheus_job]
              regex: .+
              action: keep
            - source_labels: [__meta_docker_container_name]
              regex: "/(.*)"
              target_label: container_name

logs:
  positions_directory: "/positions"
  configs:
    - name: gcloud
      clients:
        - url: "https://${uname}:${password}@logs-prod-us-central1.grafana.net/loki/api/v1/push"
      scrape_configs:
        - job_name: "docker_file"
          relabel_configs:
            - source_labels: ['__meta_docker_container_name']
              regex: '/(.*)'
              target_label: 'container'
          docker_sd_configs:
            - host: "unix:///var/run/docker.sock"
              refresh_interval: "10s"

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
    rootfs_path: /host/root
    sysfs_path: /host/sys
    procfs_path: /host/proc
    instance: ${host}

